### ISSUE TITLE
Resulting War Cards Not Added to Deck (players[0])

### ISSUE THREAD

**Issue by bmac12** [grecoe/teals#6]
My problem is that during doWar when either player 1 or 2 wins the cards, they are not added to the decks.

Issue:(Terminal)
[4, 5, 14, 13, 12, 2, 12, 4, 5, 8, 2, 6, 8, 2, 14, 12, 11, 11, 11, 7, 4, 3, 10, 7, 5, 9]
[10, 2, 7, 6, 13, 13, 3, 13, 4, 5, 11, 6, 10, 14, 9, 14, 9, 6, 3, 12, 8, 8, 9, 10, 3, 7]
Turn 1
P1 = 2, P2 = 4
Player 1 Cards Total 25
Player 2 Cards Total 25
Turn 2
P1 = 5, P2 = 11
Player 1 Cards Total 24
Player 2 Cards Total 26
Turn 3
P1 = 13, P2 = 6
Player 1 Cards Total 23
Player 2 Cards Total 27
Turn 4
P1 = 5, P2 = 9
Player 1 Cards Total 24
Player 2 Cards Total 26
Turn 5
P1 = 14, P2 = 3
Player 1 Cards Total 23
Player 2 Cards Total 27
Turn 6
P1 = 5, P2 = 3
Player 1 Cards Total 24
Player 2 Cards Total 26
Turn 7
P1 = 9, P2 = 10
Player 1 Cards Total 25
Player 2 Cards Total 25
Turn 8
P1 = 12, P2 = 9
Player 1 Cards Total 24
Player 2 Cards Total 26
Turn 9
P1 = 8, P2 = 14
Player 1 Cards Total 25
Player 2 Cards Total 25
Turn 10
P1 = 11, P2 = 13
Player 1 Cards Total 24
Player 2 Cards Total 26
Turn 11
P1 = 6, P2 = 4
Player 1 Cards Total 23
Player 2 Cards Total 27
Turn 12
P1 = 10, P2 = 10
Player 1 Cards Total 24
Player 2 Cards Total 26
war
#each time there is a war the total cards of players 1 and 2 go down by 10 (50 to 40 to 30 and so on, 2 cards are face up)
Turn 13
P1 = 14, P2 = 2
Player 1 Cards Total 19
Player 2 Cards Total 21
Turn 14
P1 = 7, P2 = 7
Player 1 Cards Total 20
Player 2 Cards Total 20
war
Turn 15
P1 = 4, P2 = 6
Player 1 Cards Total 15
Player 2 Cards Total 15
Turn 16
P1 = 4, P2 = 2
Player 1 Cards Total 14
Player 2 Cards Total 16
Turn 17
P1 = 13, P2 = 7
Player 1 Cards Total 15
Player 2 Cards Total 15
Turn 18
P1 = 9, P2 = 8
Player 1 Cards Total 16
Player 2 Cards Total 14
Turn 19
P1 = 6, P2 = 4
Player 1 Cards Total 17
Player 2 Cards Total 13
Turn 20
P1 = 13, P2 = 2
Player 1 Cards Total 18
Player 2 Cards Total 12
Turn 21
P1 = 3, P2 = 11
Player 1 Cards Total 19
Player 2 Cards Total 11
Turn 22

import random

def createPlayerDecks(shuffle_count=7):
    card_face = [2,3,4,5,6,7,8,9,10,11,12,13,14]
    deck = []

    # Step 1: Create the deck 
    for i in range(4):
        for card in card_face:
            deck.append(card)

    # Step 2: Shuffle it a number of times
    for i in range(shuffle_count):
        random.shuffle(deck)

    # Step 3: Deal them out
    players = [[],[]]
    for i in range(len(deck)):
        players[i % 2].append(deck[i])

    return players
    
players = createPlayerDecks()
print(players[0])
print(players[1])

def doWar(player_deck1, player_deck2, war_count):
 
    player1_flip = None
    player2_flip = None
    risk_cards = []

    if len(player_deck1) < war_count + 1:
        risk_cards.extend(player_deck1.copy())
        player_deck1.clear()
        player2_flip = player_deck2[-1]
    elif len(player_deck2) < war_count + 1:
        risk_cards.extend(player_deck2.copy())
        player_deck2.clear()
        player1_flip = player_deck1[-1]

  
    if len(player_deck1) and len(player_deck2):
       
        for i in range(war_count):
            risk_cards.append(player_deck1.pop())
            risk_cards.append(player_deck2.pop())

        '''
            Get the final card they will flip, also added to the risk cards
        '''
        player1_flip = player_deck1.pop()
        player2_flip = player_deck2.pop()
        risk_cards.extend([player1_flip, player2_flip])

    while player1_flip == player2_flip:
        print("Continuation War")
        player1_flip, player2_flip, risk = doWar(player_deck1, player_deck2, war_count)
        risk_cards.extend(risk)

    return player1_flip, player2_flip, risk_cards
    
def prependCards(deck, cards):
    while len(cards):
        deck.insert(0,cards.pop())

# Create the player decks
players = createPlayerDecks(7)
# Track number of turns
turns = 0
max_turns = 400

while len(players[0]) and len(players[1]):

    turns += 1
    print('Turn', turns)
    if turns >= max_turns:
        break

  

    p1Card = players[0].pop()
    p2Card = players[1].pop()
    current_cards = [p1Card, p2Card]
    print("P1 = {}, P2 = {}".format(p1Card,p2Card))
    print('Player 1 Cards Total', len(players[0]))
    print('Player 2 Cards Total', len(players[1]))

    if p1Card > p2Card:
        prependCards(players[0], current_cards)
    elif p2Card > p1Card:
        prependCards(players[1], current_cards)
    else:
        print("war")
        p1, p2, risk = doWar(players[0], players[1], 3)

winner_list = None
if not p1 or (p2 and p1 < p2):
    winner_list = players[1]
elif not p2 or (p1 and p1 > p2):
    winner_list = players[0]

prependCards(winner_list, risk)
prependCards(winner_list, current_cards)

winner = None
if len(players[0]) and len(players[1]):
    if len(players[0]) > len(players[1]):
        winner = "Player 1"
    else: 
        winner = "Player 2"
else:
    winner = "Player 1" if len(players[0]) > 0 else "Player 2"

    print("{} wpm the game in {} turns".format(winner, turns))
    print(len(players[0]), len(players[1]))

**Comment by grecoe** [comment]
Hi Brady, 

If you look at the code here: https://github.com/grecoe/teals/issues/3 I updated it with comments to describe it. 

One thing I call out, but am not totally clear on (and that's my fault) is when I list out the returns in the function doc string:

```python
'''
        result[0] - Flip card of the player1 after flipping the war_count cards, or
                    None if player 1 does not have enough cards and forfiets. 
        result[1] - Flip card of player 2 after flipping the war_count cards, or
                    None if player 2 does not have enough cards and forfiets. 
        result[2] - All of the cards, including the flip cards, that are at risk. 
'''
```

It is up to the caller of the function (you) to add the cards to the winners deck. So when you make the call:

```python
   p1, p2, risk = doWar(players[0], players[1], 3)
```
You get the final card from both player 1 (p1), player 2 (p2) and all the cards that were part of the war (risk), but not including the cards that started it. 

With those returns, you need to check the returns and add the <b>risk</b> cards to the winners deck with the prependCards() call. You also need to add the two cards that started the war in the first place. 

So, how do you check?

| State | Description |
|-------|--------------|
|p1 == None| p1 has forfeited and the risk cards get added to p2's deck|
|p2 == None| p2 has forfeited and the risk cards get added to p1's deck|
|p1 < p2| p1 has lost and the risk cards get added to p2's deck|
|p2 <  p1| p2 has lost and the risk cards get added to p1's deck|

So you are right, the cards from the war are not added to the winning players deck EVER inside the war function. That's up to you to do once the function returns results to you.

Does this make sense?

**Comment by grecoe** [comment]
Another thing I noticed is after the first turn there were only 50 cards. Did you forget to add them to the winners deck?
