### ISSUE TITLE
Code not running properly. 

### ISSUE THREAD

**Issue by joseph-bono** [grecoe/teals#8]
hour = input("What hour of the day is it? ex:10am or 6pm: ")

if hour == "7am" :
  print("You should be getting ready for school.")

elif hour == "8am" or "9am" or "10am" or "11am" or "1pm" or "2pm" :
  print("You should be at school.")

elif hour == "12pm" :
  print("You should be at lunch.")

elif hour == "3pm" or "4pm" or "5pm" or "6pm" or "7pm" or "8pm" or "9pm" :
  print("You should be home, out of school")

else:
  print("You should be asleep.")

No matter what time I put in, except 7am, the code will always print "You should be at school" and I can't figure out why. If you are able to figure it out can you please email me at joseph.bono@eths.education. 
Thank you, 
Joey Bono

**Comment by grecoe** [comment]
Hi Joseph, 

Sorry for not getting back sooner. I see the problem in the code. Taking only the top part of it:

```python
if hour == "7am" :
    print("You should be getting ready for school.")
elif hour == "8am" or "9am" or "10am" or "11am" or "1pm" or "2pm":
```

If I enter in "7am" then the if part of your statement is true and it prints "You should be getting ready for school."

However if I enter ANYTHING else, the first elif is hit. Why? Well lets break this down:

```
elif hour == "8am" or "9am" or "10am" or "11am" or "1pm" or "2pm":

Is the equivalent of:
1. (hour == "8am") -> True if "8am" is entered
2. ("9am") -> True always because "9am" is a valid value.
No need to go any further!
```

So break down your initial statement:
```
Input is "12pm"

elif hour == "8am" or "9am" or "10am" or "11am" or "1pm" or "2pm":
elif ("12pm"== "8am") or ("9am") or ("10am") or ("11am") or ("1pm") or ("2pm"):
elif false or true or true or true or true or true:

Knowing boolean math:
false or true or true or true or true or true == true
```

What you have to change is comparing hour to each of the values in your elif statement like this
```
elif hour == "8am" or hour == "9am" or hour == "10am" or hour == "11am" or hour == "1pm" or hour == "2pm":
```

**Comment by grecoe** [comment]
Talked with Joseph, all set.
